#ifndef MODULESMANAGER_GLOBAL_H
#define MODULESMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULESMANAGER_LIBRARY)
#  define MODULESMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define MODULESMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULESMANAGER_GLOBAL_H
