#ifndef PLUGINSMANAGER_GLOBAL_H
#define PLUGINSMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINSMANAGER_LIBRARY)
#  define PLUGINSMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINSMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSMANAGER_GLOBAL_H
