#pragma once

#include <QtCore/qglobal.h>

#if defined(RESOURCEMANAGERMODULE_LIBRARY)
#define RESOURCEMANAGERMODULE_EXPORT Q_DECL_EXPORT
#else
#define RESOURCEMANAGERMODULE_EXPORT Q_DECL_IMPORT
#endif
